run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - typecheck     # Type-check Go code
    - unused        # Check for unused code
    - gofmt         # Check formatting
    - goimports     # Check import formatting
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security checker
    - goconst       # Find repeated strings that could be constants
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - prealloc      # Find slice declarations that could be preallocated

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    check-shadowing: true
    enable-all: true

  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G104  # Allow unhandled errors in some cases
      - G304  # Allow file path from variable (needed for config)

  goimports:
    local-prefixes: github.com/SongRunqi/go-todo

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst

    # Exclude known issues in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
